### ISSUE TITLE
Directive - Get random value from array 

### ISSUE THREAD

**Issue by marcpre** [EFTEC/BladeOne#100]
Hello,

first: Thx for this awesome standalone version!

I am using `"eftec/bladeone": "^3.33",` and `PHP 7.1.33`.

I am trying to create a function that picks a random value from an array. For this case I tried to create a directive, such as:

```
                $views = __DIR__ . '/views';
                $cache = __DIR__ . '/cache';
                $blade = new BladeOne($views, $cache, BladeOne::MODE_AUTO);

                $blade->directive('randomValFromArr', function ($array) {
                    $val = array_rand($array, 1);
                    return "<?php $array[$val]; ?>";
                });
```

I want to use the function in my view  - `test.blade.php` the following ways: 

```
randomValFromArr(["a", "b", "c"]); // should return a random value back

randomValFromArr(["a",{{$title} , "c"]); // should either return a random value or value that is passed to the template back

```

I am currently get nothing back.

Any suggestions what I am doing wrong in defining the directive?

I appreciate your reply!

**Comment by jorgecc** [comment]
$blade->directive('randomValFromArr', function ($array) {
                    $val = array_rand($array, 1);
                    return "<?php $array[$val]; ?>";
                });

If you do a var_dump on the function, you will see than $array is a string.  

This line is executed at compile time:

                 $val = array_rand($array, 1);

while this line: shows the array at runtime.

                    return "<?php $array[$val]; ?>";

You could change the directive as

```
$blade->directive('randomValFromArr', function ($expression) {
    return '<?php $array='.$expression.'; $val = array_rand($array, 1); echo $array[$val]; ?>';
});

```
Example:  @randomValFromArr(["a", "b", "c"])
1) $expression (at compile time) is equals to ["a", "b", "c"]
2) So it will execute (at run time) the next operation

            <?php $array=["a", "b", "c"]; $val = array_rand($array, 1); echo $array[$val]; ?>
3) You must not forget to "echo".


And you could call it in the template as

              @randomValFromArr(["a", "b", "c"])

or

           @randomValFromArr(["a",$title, "c"])
