### ISSUE TITLE
How can I use the trios to make a optgroup

### ISSUE THREAD

**Issue by Ihabafia** [EFTEC/BladeOne#101]
Hi,

Your repo is really great and helpful.  But I couldn't able to create a group select with the BladeOneHtml.

Could you please have an example so that I can use it as a model.

Thank you,

**Comment by jorgecc** [comment]
There is an example of it

Code:

https://github.com/EFTEC/BladeOne/blob/master/examples/testbootstrap.php

The data of each row looks like:

```php
$countries=array();
$country=new stdClass();
$country->id=1;
$country->cod='ar';
$country->name="Argentina";
$country->continent="America";
$countries[]=$country;
$country=new stdClass();
$country->id=2;
$country->cod='ca';
$country->name="Canada";
$country->continent="America";
$countries[]=$country;
$country=new stdClass();
// ....
```

View:

https://github.com/EFTEC/BladeOne/blob/master/examples/views/TestBS/hellobootstrap.blade.php

```html

@selectgroup('id1',"class='object' multiple='multiple' size='5'")
@trio('0','--Select a country--','')
@trios($countries,'id','name','continent',$multipleSelect)
@endselect()
```
