### ISSUE TITLE
How to use fetch

### ISSUE THREAD

**Issue by hoangnamitc** [EFTEC/BladeOne#102]
hi,

Smarty Template have Method Fetch().

Does that mean assign value to template and view content file in php code.

The same like 

`
@include('view.abc', ['key' => 'value'])
`

But is echo in php:

`<?php
echo $blade->xxx('view.abc', ['key' => 'value'])
`

how to do it?

Thanks!

**Comment by jorgecc** [comment]
`$values=$blade->run('view.abc',[]);`

Now if you want to do it inside the template, then you could create a function

```
function myFunction() {
       $values=$blade->run('view.abc',[]);
       // do some stuff
      return $something
}
```

and in the template use 

`{!! myFunction() }}`

There is also a $blade->runString('......',[]); // but instead of reading a template, it compile the text.

**Comment by hoangnamitc** [comment]
Hi,
Bro no, i want use in code php but not teamplate, and can not use $blade->run() because it used for master layout.

I want get content of only one file template for php code and can passing data for only this file. After echo.

Example: i want array() passing to file template after run loop and echo via ajax?

**Comment by jorgecc** [comment]
you can use $blade->run() with any template.  
If not, you can use $blade->runString() to run a string. So you could open the template manually,  
 load in a string and call this method.
If not, you can use $blade->runChild() to run a template without creating a new section.  

What do you really want to do?.

**Comment by hoangnamitc** [comment]
Thanks bro, can use ->runChild() , but this method can passing array data to template ?

**Comment by jorgecc** [comment]
yes, it is used when we call @include("template",[]) we are calling echo $this->runChild("template");

**Comment by hoangnamitc** [comment]
I do not understand, @include() use in template, how to i can passing array() data into template from php via ->runChild() ?

**Comment by jorgecc** [comment]
$this-runChild("template",$yourarray);

**Comment by hoangnamitc** [comment]
Thanks bro, let me try it...
