### ISSUE TITLE
Issues SetAliasClasses

### ISSUE THREAD

**Issue by hoangnamitc** [EFTEC/BladeOne#104]
Hi,

I code follow README, i use 

`
$blade->setAliasClasses(['SomeClass'=>'\namespace1\namespace2\SomeClass']);
`

inside template issues :

if use: 
`{{SomeClass::Method()}}` is OKE

but use:
`@if ({{SomeClass::Method()}})`  ==> not working 

Uncaught Error: Class 'SomeClass' not found

Thank

**Comment by jorgecc** [comment]
> @if ({{SomeClass::Method()}})

You are using scripting inside another scripting and I don't know if it works.

You must do instead

>  @if(SomeClass:Method());

Also, setAliasClasses only works with {{SomeClass::method}} , @SomeClass::method() and {!! SomeClass::method() !}}

You coud use

> @if(\namespace1\namespace2\SomeClass:Method());

or

> @use(\namespace1\namespace2)
> @if(SomeClass:Method());

**Comment by hoangnamitc** [comment]
Hi bro,
At first i am use is:

> @inject('Some', '\namespace1\namespace2')
> @if($Some::Method())

is working oke, but every file blade must be declared 
> @inject('Some', '\namespace1\namespace2')

I thought setAliasClasses is passing Classes Global. 

because the way I do it is the same, similar:

> @use(\namespace1\namespace2)
> @if(SomeClass:Method());

**Comment by jorgecc** [comment]
The method setAliasClasses is limited because it does not want to impact the performance, so it is one of the features of Laravel's blade and Bladeone but for this case, it also a limit.

Since you are doing an if, then you could also calculate it on the server (that it is the recommended behavior).

```
$isValid=\namespace\SomeClass::method();
echo $blade->run('folder.template',['isvalid'=>$isvalid];
```
and

```
@if($isvalid) 
// your code
@endif
```
