### ISSUE TITLE
@method(PUT) now working anymore

### ISSUE THREAD

**Issue by Ihabafia** [EFTEC/BladeOne#105]
Hello,

First, I would like to thank you for offering this great tool.
Second, I was using the @method('PUT') in Laravel, but when I start using it here it didn't work, then I found out that it will work if I did it as @method(PUT).

But now, it seems to be after an update it stopped working and it starts to show in the view as is instead of getting replaced with <input type='hidden' name='_token' value='PUT'>

Could you please help me to know how can I send a PUT or DELETE method forms.

Thank you,

**Comment by jorgecc** [comment]
ok, returned.

html does not allow to use 

<form method="put">

So instead, this function uses a hidden field (_method) with the value PUT or DELETE.
