### ISSUE TITLE
Cache file is still used when template file has already been deleted

### ISSUE THREAD

**Issue by Connum** [EFTEC/BladeOne#106]
I have a little issue when using an array of paths for the views.

**Steps to reproduce**:
1. Using an array of possible paths as the `$blade_views` in the constructor
```php
$Blade = new BladeOne(
  array(
    './child_views',
    './parent_views',
  ),
  './cache',
  BladeOne::MODE_AUTO
);
```
2. Creating both `./child_views/test.blade.php` and `./parent_views/test.blade.php`
3. Calling
```php
$Blade->run('test', array());
```
> As expected, the engine uses `./child_views/test.blade.php`.

4. Deleting `./child_views/test.blade.php` and running the code in 3 again

**Result:**
The cached file of the version in `child_views` is still being used.

**Expected result:**
The cache is updated from the template file in `parent_views`.

**Comment by jorgecc** [comment]
Ok, let's me check this one.

**Comment by jorgecc** [comment]
It's not a bug.

* **Template1.blade.php** 01-01-2010 10:00
* **Template2.blade.php** 01-01-2010 10:05
* **Compiledfile.php** 01-01-2010 10:30

1. Is template1 recent than compiled? No.
2. Is template2 recent than compiled? No.
3. Then, it is not recompiled.

Then, if template1 is deleted, we have

1. Template1 is gone, so it is not even considered.
2. Is template2 recent than compiled? No.
3. Then, it is not recompiled.

**Comment by Connum** [comment]
> Template1 is gone, so it is not even considered.

That's the part that doesn't seem to work for me! Let me see if I can provide a simplified example repository...

**Comment by jorgecc** [comment]
I did an example. 

https://github.com/EFTEC/BladeOne/blob/master/examples/testingcompile.php
