### ISSUE TITLE
Remove Laravel dependencies

### ISSUE THREAD

**Issue by m-mohr** [EFTEC/BladeOne#11]
There are some Laravel dependencies, like calls to `app()` or `Illuminate`. As BladeOne usually only makes sense outside of Laravel environments, it doesn't make sense to keep them in the code. Therefore they should be removed.

**Comment by jorgecc** [comment]
I checked the code and there is not a single call or use to app() or  Illuminate but a reference in the documentation.

Anyways, this code runs fine without Laravel.

**Comment by m-mohr** [comment]
Look at PR #10, there  you can find them in the changes, but as you integrated them they are already removed now. Thanks.
