### ISSUE TITLE
Blade X features

### ISSUE THREAD

**Issue by lexdubyna** [EFTEC/BladeOne#110]
Hello!
Just a question: will the package have new Blade X features (like `x-components` with `@props`) at any point in the future?

**Comment by jorgecc** [comment]
Hi there:

It's not planned.
Blade (and BladeOne) has 3 ways to do the same operation and with x-components, we will have a fourth way.  

But my main complaint is performance. It's not performance-wise. For example, the command props (used in some cases) use get_defined_vars() and it creates a new array with all the variables available, while it's life is short but it's an overhead for a simple operation that it could be executed many times per templates.

It also adds dependencies to mbstring.  MbString is worth it if we use mime language but it's useless for utf-8 languages.   Bootstrap (AFAIK), works with mbstring (optionally), while laravel is mandatory.

**Comment by lexdubyna** [comment]
I see, thanks for the feedback!
