### ISSUE TITLE
the template extends doesn't work  

### ISSUE THREAD

**Issue by yemaozi999** [EFTEC/BladeOne#113]
![image](https://user-images.githubusercontent.com/16147749/82001767-863eb380-968e-11ea-8ee1-17173761e8ce.png)

![image](https://user-images.githubusercontent.com/16147749/82001829-aff7da80-968e-11ea-881c-255cd45547c4.png)

![image](https://user-images.githubusercontent.com/16147749/82001845-bb4b0600-968e-11ea-8667-b99c1071afb1.png)

the template extends doesn't work

**Comment by jorgecc** [comment]
Hi:

There is an example in the folder examples:

examples\test2b.php

that does the same job


examples\views\Test\hello2.blade.php

```html
@extends('Shared.newlayout')

@section('content')
    <div style="background-color: rosybrown">
    {{$other}} {{$v1}}
    <br>IT IS THE SECTION CONTENT<br>
    <br>
    <br>
    <br>END OF THE SECTION CONTENT
    </div>
@stop


@section('footer')
    <div style="background-color: darkred">
   IT IS THE SECTION FOOTER<br>
   <br>
   <br>
   <br>END OF THE SECTION FOOTER
    </div>
@stop
```

examples\views\Shared\newlayout.blade.php
```html
<html>
<head>
</head>
<body>
<h1>Test</h1>
This example shows the use of @@extends, and @@yield<br><br>
    @yield('header','<br>header content is missing<br>')
    @yield('content')
    @yield('footer')
    
</body>
</html>
````



![blog1](https://user-images.githubusercontent.com/9570242/82004147-30d3b980-9630-11ea-8863-19aa98559c6b.jpg)

**Comment by yemaozi999** [comment]
emm, is my mistake, its ok now, thanks
