### ISSUE TITLE
View Composers?

### ISSUE THREAD

**Issue by KeironLowe** [EFTEC/BladeOne#117]
Apologies if this is mentioned somewhere, but I've had a look through the docs and I can't find any mention of it. Does BladeOne support View Composers? It isn't mentioned in the [differences](https://github.com/EFTEC/BladeOne/wiki/Differences-between-Blade-and-BladeOne) page so I would have thought it is, but I can't find any documentation for it.

Thanks!

**Comment by jorgecc** [comment]
Hi there:

Usually, I don't think to add features that rely on functionalities of Laravel but I am evaluating adding this one. If I don't have personal troubles this week (I hope not to jinx myself), then I could add it during this week.

**Comment by jorgecc** [comment]
Done in 3.45.1

https://github.com/EFTEC/BladeOne/wiki/Injecting-logic-before-the-view-(composer)

It misses "View Creators" Because BladeOne does not have the definition of an instance of the view.

**Comment by KeironLowe** [comment]
Amazing, thanks for the quick response!
