### ISSUE TITLE
Not loading blade from parent folder from @extends

### ISSUE THREAD

**Issue by krowst** [EFTEC/BladeOne#120]
Hi Jorge
Method @extends('layouts.backend') into template not loading parent blade

Structure of folders look like this
- layouts (folder)
    - backend.blade
- request (folder)
   - consultation.blade 

So it's show the error:
BladeOne Error [Read file]:
Template not found :layouts.backend 

Can you help to fix this issue? or any advice if I've missed something?
Much appreciated

P/s/ the library is seems really good though, except this ..

**Comment by jorgecc** [comment]
For starter, you should try to run in Debug Mode because it shows you more information about the folder.

$bladeOne=new BladeOne($views, $cache, BladeOne::MODE_DEBUG);

**Comment by krowst** [comment]
Yes, I was trying to do that, but it's not give anything additional

Only this:
BladeOne Error [Read file]:
Template not found :layouts.backend on file:

If I will move for example file backend.blade.php to the same folder  - request, it's load this blade with no problems at all, but not in different directory ...

**Comment by krowst** [comment]
I have found why is it happening, it because the current logic looking the folder inside the current directory only.. but it should, on the contrary, go beyond the current folder ..

I have added x2 line for locateTemplate() and now it's works for me

    private function locateTemplate($name)
    {
        if ( strpos($name, '/')) 
            $name = '../'.$name;

**Comment by jorgecc** [comment]
I added an example:

https://github.com/EFTEC/BladeOne/blob/master/examples/example_extends.php

```php
$bladeOne=new BladeOne(__DIR__.'/views', __DIR__.'/compiles', BladeOne::MODE_DEBUG);
echo $bladeOne->run('exampleextends.example', ['title'=>$title,'content'=>$content]);
```

https://github.com/EFTEC/BladeOne/blob/master/examples/views/layout/mylayout.blade.php

```php
@extends('layouts.mylayout')
@section('title', $title)
@section('content')
    @parent
    {{$content}}
@endsection

```

https://github.com/EFTEC/BladeOne/blob/master/examples/views/exampleextends/example.blade.php

```php
@extends('layouts.mylayout')
@section('title', $title)
@section('content')
    @parent
    {{$content}}
@endsection
```




And it doesn't need to change the method locatetemplate(). A common mistake is when we specify the initial folder

Usually, this library works as:

```php
$bladeOne=new BladeOne();
```

And it sets the folders automatically, But we could specify the folder using ```__DIR__```

```php
$bladeOne=new BladeOne(__DIR__.'/views', __DIR__.'/compiles', BladeOne::MODE_DEBUG);
```

Or in some cases, we need to specify the whole folder

```php
$bladeOne=new BladeOne('/var/web/views', 'var/web/compiles', BladeOne::MODE_DEBUG);
```

**Comment by krowst** [comment]
Thanks Jorge, all clear enough, my mistake... All works!
