### ISSUE TITLE
String filters?

### ISSUE THREAD

**Issue by MorevM** [EFTEC/BladeOne#122]
Hi!
First of all, many thanks for your work. :)

I worked in the past with Twig, and I really like the functionality of the filters (for example: [https://twig.symfony.com/doc/2.x/filters/capitalize.html](https://twig.symfony.com/doc/2.x/filters/capitalize.html)

The Blade syntax is much cleaner than Twig and I enjoy, but exactly this feature looks a lot clearer than directives. And also there is no way to nest directives like 
`{{ @toJPG(@resize('image.jpg', 300, 300)) }}`

There is custom implementation: [https://github.com/thepinecode/blade-filters](https://github.com/thepinecode/blade-filters)

So, what do you think about? 
I saw your opinion about dot notation [here](https://github.com/EFTEC/BladeOne/issues/98), but maybe something changes? :)

If not, can you please make compile*Echos methods private instead protected?
Thanks! 

[Edited]
Also, for backward compatibility and to be compatible with the Blade spirit (`Everything inside {{ }} is practically php`) maybe we can extend class with other tags? 
For example with square brackets `[[ 'string' | capitalize ]]` or smth similar.

**Comment by jorgecc** [comment]
I was thinking the same.

Added 3.46

https://github.com/EFTEC/BladeOne/wiki/Template-Pipes-(Filter)

**Comment by MorevM** [comment]
Wow, it was really fast. :) 
Thank you so much for the quick response!
