### ISSUE TITLE
difficulty in finding documents

### ISSUE THREAD

**Issue by kythuatwebso** [EFTEC/BladeOne#123]
Hello,

Currently I find the documentation of this package (wiki) quite difficult to read and search for keywords.

Thanks.

**Comment by jorgecc** [comment]
Hi there:
If you want to know the tags, then, you could check the official documentation here.  However, it is not complete and some tags are not even documented.    

https://laravel.com/docs/7.x/blade

BladeOne is "binary" compatible with Laravel Blade with some exceptions (x-component and features that require Laravel).
