### ISSUE TITLE
passing data to layout page.

### ISSUE THREAD

**Issue by sodoojin** [EFTEC/BladeOne#124]
```php
// layouts/app.blade.php
{{ $header }}
@yield('content')
{{ $footer }}
```
```php
// hello-world.blade.php
@extends('layouts.app')

@section('content')
    test!
@endsection
```

I want to pass header and footer data to app.blade.php.
so i did like below

```
$blade->composer('layouts.app', function($view) {
    $view->with([
        'header' => ci_module_run('common', '', 'header'),
        'footer' => ci_module_run('common', '', 'footer'),
    ]);
});

$blade->run('hello-world');
```

but app.blade.php received nothing.

https://github.com/EFTEC/BladeOne/blob/cc9c31bc8b94e7075184713ac76ad8c2396dd2cd/lib/BladeOne.php#L1000-L1005

i guess  only bladeone's target page is allowed to receive composed data.
is there a way to pass the data to layout page?

**Comment by jorgecc** [comment]
The method composer is working with the main template but it doesn't work with the extended template.

Fixed in 3.46.3
