### ISSUE TITLE
@embed

### ISSUE THREAD

**Issue by K1ll3rM** [EFTEC/BladeOne#125]
Hello, I really like using BladeOne but how would I implement a `@embed` directive? It's the only feature I really miss from twig but I wouldn't know hwo to make it work with `@section`.

**Comment by jorgecc** [comment]
Hi there:
 
Ok, I promise nothing but I will look at it.

My main gripe is I don't want to

* break @extends  
* or hurts the performance of existing projects.

**Comment by K1ll3rM** [comment]
Thanks that would be very nice to have, even the original blade doesn't have it which is kind of annoying.

**Comment by jorgecc** [comment]
The tags \@components/\@slot do the same job. Those tags already exist but they weren't documented:

https://github.com/EFTEC/BladeOne/wiki/Template-Component
