### ISSUE TITLE
@resource('js/jquery.js')   seems doesn't   work

### ISSUE THREAD

**Issue by yemaozi999** [EFTEC/BladeOne#126]
![image](https://user-images.githubusercontent.com/16147749/94231120-f3fcc500-ff35-11ea-8106-f78c28a30cc4.png)

**Comment by jorgecc** [comment]
It was an error. it is called @relative

https://github.com/EFTEC/BladeOne/wiki/Template-Asset,-Relative,-Base-and-Canonical-Links
