### ISSUE TITLE
Using if logic with static method

### ISSUE THREAD

**Issue by PlanetTheCloud** [EFTEC/BladeOne#129]
Hi,

I have a Session class which I've aliased.
If I use it as a variable: `{{ Session::user('username') }}` it works as expected. 
But if I use it inside an `if`: `@if ( Session::user('has_2fa') )`, it will throw an exception:
`Fatal error: Uncaught Error: Class 'Session' not found in <path to cache>`.

Is there a way I could call a static method with `if` or other conditional logic?
Thank you.

**Comment by jorgecc** [comment]
Sorry for the delay.

You should look at it

https://github.com/EFTEC/BladeOne/wiki/Template-calling-methods


You could use 

```php
@use(\namespace1\Session) 
{{ Session::user('username') }}
```
at the top of your template

Or if you want to use a variable (instead of a class), then you could use

```php
@inject('metrics', 'App\Services\MetricsService')
{{ $metric->monthlyRevenue() }}
```

or you could use the full name of the class


```php

{{ namespace\Session::user('username') }}
```
