### ISSUE TITLE
Include Parameters are Shared Too

### ISSUE THREAD

**Issue by joao-oliveira-nex** [EFTEC/BladeOne#132]
Sorry for bothering again. :)

This is follow-up to the issue:
#131 

So, the problem with the @component method is solved, but not with the **@include** one.

Should the @include share the parameters?

Thanks in advance!

**Comment by jorgecc** [comment]
ok, changed in 3.49

By default, it won't work (arguments will work globally, i.e. everywhere) but if we set $blade->includeScope=true; then the arguments will be limited to the call of the include.

https://github.com/EFTEC/BladeOne/wiki/Template-inheritance
