### ISSUE TITLE
[optimization] use is_dir and is_file instead of file_exists

### ISSUE THREAD

**Issue by bassauer-storms-media** [EFTEC/BladeOne#133]
I experienced massive performance lacks while using the php function _file_exists_.

Searching the internet for that issue I stumbled upon this: https://github.com/symfony/symfony/issues/36493

Since I rewrote my apps to use id_dir and is_file everything works much (much) faster.

I recommend changing all file_exists calls in your code to the corresponding alternative.

**Comment by jorgecc** [comment]
It is not much faster, but it is enough to be replaced.

https://github.com/EFTEC/php-benchmarks#file_exists-vs-is_file

In Windows, file_exists is around 0.0000345 seconds  while is_file is 0.0000268 seconds
In Liinux, file_exists is around 0.0000017 seconds  while is_file is 0.00000062 seconds

Changed in 3.50

**Comment by bassauer-storms-media** [comment]
awesome, thanks!
