### ISSUE TITLE
[suggestion] compiling callbacks/hooks

### ISSUE THREAD

**Issue by bassauer-storms-media** [EFTEC/BladeOne#134]
I need to modify the content of the currently compiled file on the fly. (In my case I put event triggers that can be hookes before and after the head and body tag open and close)

So could we please have something like this please:

```
    protected $compileCallbacks = []; // (new)

    public function compile($templateName = null, $forced = false) // (nothing changed)
    {
        $compiled = $this->getCompiledFile($templateName); // (nothing changed)
        $template = $this->getTemplateFile($templateName);  // (nothing changed)
        if (!$this->isCompiled) {  // (nothing changed)
            // this part is different from BO master
            $contents = $this->compileString($this->getFile($template));
            foreach($this->compileCallbacks as $callback) {
                if(is_callable($callback))
                    $callback(&$contents, $templateName); // or use call_user_func / call_user_func_array
            }
            return $contents;
            // ---
        }
// ....
```
This way one could register callbacks that are able to modify the compiled contents.

That would be awesome!

I saw there is an "extend" method in the BladeOne class which allow one to register a custom compile callback. But the problem with that callback is, that it is triggered multiple times (in fact for every php block that opens within the compiled view). The original compile method only runs once per compiled file.

**Comment by jorgecc** [comment]
Ok.

Example: It converts the compiled result into uppercase

```php
$blade->compileCallbacks[]= static function (&$content, $templatename=null) {
   $content=strtoupper($content);
};
```

**Comment by bassauer-storms-media** [comment]
Awesome!!!! Thank you so so so much!

I really appreciate your work!

Thanks!
