### ISSUE TITLE
Exception mode

### ISSUE THREAD

**Issue by abdullahezzat1** [EFTEC/BladeOne#135]
I'm trying to use BladeOne within the Symfony Framework which handles thrown exceptions automatically.

It would be better to have an extra mode where BladeOne **only throws exceptions** instead of showing the errors directly on the web via BladeOne::showError().

Thanks :heart:

**Comment by jorgecc** [comment]
I am a bit busy, but I will check it.

**Comment by jorgecc** [comment]
Ok, done. You must set the field blade->throwOnError=true;
