### ISSUE TITLE
Why do cache filenames use sha()?

### ISSUE THREAD

**Issue by mrcw** [EFTEC/BladeOne#136]
Hello!

I've just a quick question: why is it good, to use the sha(...) function with the compiled filenames inside the getCompiledFile() method?

(For me: when I have to read other server logs, it just makes harder to find out the real filenames.)

Thanks

**Comment by jorgecc** [comment]
The mode BladeOne::MODE_DEBUG does not codify the name of the archives, and it could be used to pinpoint problems.

The main problem is the folder **compile**. This folder usually is exposed to the net, so unless the developer block this folder (it could be done easily with a .htaccess file (Apache) or blocked using Nginx, any hacker could read the file if it knows the name of the file.

i.e.  this path is more predictable:
* https://someserver.dom/compile/template.bladec
than this:
* https://someserver.dom/compile/868145cb56e048a0f7e0c3c096eccde17b56dfea.bladec

**Comment by mrcw** [comment]
"folder compile - this folder usually is exposed to the net" - so if the template and its 'compile' cache folder is outside of the public_html folder (like in our system), it has no benefits for us...?

**Comment by mrcw** [comment]
?

**Comment by kezenwa** [comment]
Trying not to stat another Post unnecessarily

How's this method ` setCacheStrategy($cacheStrategy, $index = null)` used and what's the benefit. A look at the code tells me it's used by `cacheUniqueGUID($serialize = true)` which generates some strings appended to the file name generated by `getCompiledFileCache($view)` which is useful only when doing **Full Page Cache**

Now I want to know how to get the values to used in ` setCacheStrategy($cacheStrategy, $index = null)` , when to use this method and also why .

Also when would I use `getCacheStrategy()` and `writeCacheLog($txt, $nivel)`

Thanks

**Comment by jorgecc** [comment]
Solved in #4.5

I added the method setCompileTypeFileName() so we could determine how the filename will be generated. By default, the mode is the same as before (no change for DEBUG mode and SHA1 for everything else).
