### ISSUE TITLE
Including views from diffrent view folders/Multiple base paths

### ISSUE THREAD

**Issue by Stantastic** [EFTEC/BladeOne#140]
I'm working on a modular app where modules will have templates as well. It could look like this:

App:
resources/views/master.blade.php

Module:
module/views/mymodule.blade.php

How would I be able to load files dynamically from folders that are not in in the apps base template directory?

For laravels blade I found this: https://laravel.io/forum/11-08-2015-solved-render-view-from-other-path

**Comment by jorgecc** [comment]
you can use "**/**someurl/module/views.mymodule.blade.php" if you want to use an absolute path.
