### ISSUE TITLE
Overwrite existing global shared variables with the ones in the argument of the run() function

### ISSUE THREAD

**Issue by JoeSixGo** [EFTEC/BladeOne#142]
I'm trying to render a view with variables using the run function 
`$bladeOne->run('pages.products.list-productos',compact (
            'breadcrumb',
            'img_background',
            'listado_productos',
            'seo'
           )
 );`

The $seo array variable it has existing values set previously as a global variable using the share method.

I think the run method must overwrite the existing global variables with the ones passed in the run() calling.

Looking at source code in lib/BladeOne.php at line 1085  I believe it would be better to swap array_merge arguments like 
` $this->variables = \array_merge( $this->variablesGlobal, $variables);`

In the original laravel blade code the order is the same as I suggested: 

`$data = array_merge($this->factory->getShared(), $this->data);`

https://github.com/laravel/framework/blob/8.x/src/Illuminate/View/View.php line **149**

**Comment by jorgecc** [comment]
So, do I need to change it in line 1085? or in something else?

**Comment by JoeSixGo** [comment]
I think it's the only place where variables are merged. I also noticed in https://github.com/EFTEC/BladeOne/blob/master/lib/BladeOne.php#L1086

that `$this->variablesGlobal = []` clears all global variables, so if you call the run() method twice or more inside the same request to the server you have lost all global variables in the second or next calls.

I think that this line (1086) should be removed.

**Comment by jorgecc** [comment]
Solved in 4.5

**Comment by vaskolukas** [comment]
Hi, I am using version 4.7.1 and global variables overwrite local variables set in run function. 

I think `array_merge` function in this line: 

[https://github.com/EFTEC/BladeOne/blob/b912e9f060aaa999c0ac2fcf4b40f7a8e6cd66c0/lib/BladeOne.php#L1109](url) 

should be reversed like this:

`$this->variables = \array_merge($this->variablesGlobal,$variables);` 

so global variables would be replaced with local variable in run runction. But i am not sure if its the case. Could you maybe look into that once more?
