### ISSUE TITLE
CSRF directive does not create token

### ISSUE THREAD

**Issue by GlennBags** [EFTEC/BladeOne#145]
Not sure if a bug, however, not finding much in the way of instructions on instantiating the CSRF. 
The only thing I had to go on what the test code:
`$isvalid=$blade->csrfIsValid(true, '_mytoken'); // a) for get= it generates a new token, b) for post, it validates the token.`

States that the get should generate, but I did not find that. In my view I have
`@csrf('token')` /* as I wanted to not have the underscore in the name; not sure if that's the issue..? */

But when I inspect, there's no value.

If, however, in my View controller, I call the `getCsrfToken(true, 'token')`, then I find the hidden input set.

Am I doing something wrong?

**Comment by jorgecc** [comment]
Ok, let's me check it.

**Comment by GlennBags** [comment]
Were you able to find out? 
ATM, we're just going ahead and calling `getCsrfToken` before the run, but wasn't sure we should be having to do that.
