### ISSUE TITLE
Can't clear view file cache?

### ISSUE THREAD

**Issue by GlennBags** [EFTEC/BladeOne#146]
Would have created a "discussion", but couldn't find how to start one, so opening as "issue". 

Cannot find how to clear cache, or there's an issue with updating. 

I added code to a view file that is not recompiling. 
I'm trying to trace down an error that I'm getting, so added a dump to the file, but just keeps getting routed to the same cache file. 
I tried to remove the cache file, but gets recreated with the old content; ie no dump that I inserted into the view file.

Is there a way to clear the cache files similar to Laravel's `php artisan view:clear`

**Comment by GlennBags** [comment]
Error on my part regarding the file not updating, was hitting the wrong file.

Would still like to know if there's a means to clear the cache files, other than just deleting them.

Thanks

**Comment by jorgecc** [comment]
Ok, I added a new version with CLI where :

* we could delete the cache
* we could check the folders (permissions, etc.)

**Comment by GlennBags** [comment]
Awesome! Example usage?

**Comment by jorgecc** [comment]
in the root folder
php vendor/lib/eftec/bladeone/lib/BladeOne.php -clearcompile
