### ISSUE TITLE
Render view for sitemap

### ISSUE THREAD

**Issue by zaingithub** [EFTEC/BladeOne#15]
Hello, i have a problem with header content-type.

    function sitemap()
    {
		header("Content-Type", "text/xml");
                header("HTTP/1.1 200 OK");		
		$data['sitemap']  	= my_sitemap();
		echo $this->blade->run("sitemap", $data);
    }

I check the sitemap validity, but it always return text/html.

**Comment by m-mohr** [comment]
Not a problem with BladeOne, check http://php.net/manual/de/function.header.php how to use header() function properly.

**Comment by jorgecc** [comment]
I added an example of json.
In the php file
...
$drinks= array('Cocacola','Pepsi','Fanta','Sprite','7up');
$json=json_encode($drinks);
header('Content-Type: application/json');
echo $blade->run("TestJson.example",['json'=>$json]);

in the template example.blade.php
{!! $json !!}

**Comment by zaingithub** [comment]
Thank you... I set ob_start(); before echoing the blade and it works. :)
		ob_start();
		header("HTTP/1.1 200 OK");
		header("Status: 200 OK");
		header("Content-type: text/xml");	

Anyway, your blade doesn't ignore any @media screen from css in <style> area. Can you solve it?
![screenshot_178](https://cloud.githubusercontent.com/assets/23699888/25875021/983d2174-353f-11e7-9575-6d203e25c6dd.png)

<style>
@media screen and (max-width:500px){.class_box{width:48%}}@media screen and (max-width:323px){.class_box{width:99%;height:150px}.class_box a{height:130px}ul.class_rand-text li{width:100%;float:none}}
</style>

**Comment by jorgecc** [comment]
you should escape every "@" with a double @@ , for example @@media

Based in laravel's blade
http://stackoverflow.com/questions/29450708/using-at-sign-in-php-laravel-strings
