### ISSUE TITLE
custom directives: empty string passed as expression to directive handler function when nothing was passed to the directive

### ISSUE THREAD

**Issue by bassauer-storms-media** [EFTEC/BladeOne#150]
Hey!

I just upgraded from ^3.0 to the last release of BladeOne and realized that it breaks my framework integration because calling a directive this way:
`@mydirective` 
instead of
`@mydirective(..someParamsHere..Perhaps...)`

passes an empty string as expression to the handler method of the directive:

```
$blade->directive('mydirective', function ($expression)  {
      // at this point $expression is an empty string ''   
      // (in Version ^3.0 it was NULL at this point)   
});
```

before I upgraded the $expression was `null` when the directive was called withon anything more the it's name

Is this behavior intended or is it a bug? In my optionen `null` was the better value for this scenario.

Here is the line that would need to be changed in order to correct this (if its a bug):
https://github.com/EFTEC/BladeOne/blob/f37436a33fd9a930fa56c9a2aada40ab390be069/lib/BladeOne.php#L2804

**Comment by jorgecc** [comment]
I don't see the difference in the line.

**Comment by bassauer-storms-media** [comment]
you are absolutely right - this is very strange o.ô
