### ISSUE TITLE
error

### ISSUE THREAD

**Issue by adacnvwp** [EFTEC/BladeOne#152]
{!! $name | md5 | substr:1,5 !!}   >>  php echo md5($name ); 

Compilation error, unable to work properly,

Substr does not work

**Comment by jorgecc** [comment]
Ok, solved in 4.5.1 and it was an odd problem because it was already solved.

**Comment by adacnvwp** [comment]
Because I am in China, https://packagist.org/ cannot be accessed normally. I need to use a proxy site. The cache of the proxy site is much lower than the current version. This is the reason
