### ISSUE TITLE
error

### ISSUE THREAD

**Issue by adacnvwp** [EFTEC/BladeOne#153]
{!! $name | md5 | substr:1,30 | substr:1,25 | substr:1,20 | substr:1,15 | substr:1,10 | substr:1,5 | strtoupper !!}  >>   echo md5(substr(substr(substr(substr(substr(substr(strtoupper($name )1,5 )1,10 )1,15 )1,20 )1,25 ),1,30 );

ParseError: syntax error, unexpected integer "1", expecting ")" in  .....

The code seems to be missing a bracket, and the reverse generated is wrong.
------------------

{!! $name | md5 | substr:1,30 | strtoupper !!} >> echo md5(substr(strtoupper($name ),1,30 );

ParseError: syntax error, unexpected token ";", expecting ")" in ....

The code seems to be missing a bracket, and the reverse generated is wrong.

**Comment by jorgecc** [comment]
Ok, it was a typo

it is the phpunit

```php
        $this->assertEquals('<?php echo md5(substr(substr(substr(substr(substr(substr(strtoupper($name ),1,5 ),1,10 ),1,15 ),1,20 ),1,25 ),1,30 )); ?>'
            , $this->blade->compileString('{!! $name | md5 | substr:1,30 | substr:1,25 | substr:1,20 | substr:1,15 | substr:1,10 | substr:1,5 | strtoupper !!}',["name" => "12345"]));
        $this->assertEquals('<?php echo md5(md5(md5(substr($name ,1,25)))); ?>'
            , $this->blade->compileString('{!! $name | md5 | md5 | md5 | substr:1,25 !!}',["name" => "12345"]));
```
