### ISSUE TITLE
BladeOne::getCompiledFile's hashes should include the full template path

### ISSUE THREAD

**Issue by fbett** [EFTEC/BladeOne#165]
Hi,

i reached a strange problem yesterday:
There is a project with two entry points: frontend + backend

Both share the same template directory, but use different subfolders:
- /views/frontend/...
- /views/backend/...

In both directories are at least one file having the same name:
`_header.blade.php`

Both share the same compile directory because it is the same project (but the BladeOne instance was configured to use two different template paths).

The result was a frontend header shown when accessing the backend entry point.

The reason is, that the result from `BladeOne::getCompiledFile` has no full path dependency. The generated hash includes only the part after the template path.

Here is my solution to this:
````
public function getCompiledFile($templateName = ''): string
{
        $templateName = (empty($templateName)) ? $this->fileName : $templateName;

        $fullPath = $this->getTemplateFile($templateName);
        if($fullPath == '') {
            $this->showError('getCompiledFile', 'Template not found: ' . $templateName, true, true);
        }

        $style=$this->compileTypeFileName;
        if ($style==='auto') {
            $style='sha1';
        }
        $hash = \sha1($fullPath);
        switch ($style) {
            case 'md5':
                $hash = \md5($fullPath);
        }

        return $this->compiledPath . '/' . basename($templateName) . '_' . $hash . $this->compileExtension;
}
````

There are some changes:
- A hash including the full path is required for each style - otherwise we will have again some collision
- Style nochange/normal merged to md5/sha and removed

The result looks pretty readable to me:
- `_header_[hash].bladec`
- `Directory.View_[hash].bladec`

I have added basename() for some security reasons - for the case there is a forbidden character - but it could be unnecessary.

What do you think?
Are there normal circumstances when getTemplateFile will not return a valid template file path, but getCompiledFile`s result is expected?

If you consent, i could send a pull request.

**Comment by jorgecc** [comment]
ok, do a push.
ps: for some odd reason, I didn't receive any notification of this comment.
