### ISSUE TITLE
Small note for cleanup: Param $isParent @ runInternal is never used

### ISSUE THREAD

**Issue by bassauer-storms-media** [EFTEC/BladeOne#169]
The method `runInternal` may be passed a variable called `$isParent`. This variable is never used anywhere.

https://github.com/EFTEC/BladeOne/blob/b912e9f060aaa999c0ac2fcf4b40f7a8e6cd66c0/lib/BladeOne.php#L1095

**Comment by bassauer-storms-media** [comment]
Another thing is that the value passed into $runFast is not a boolean but always an integer (which of course evaluates to bool - but the doc comment is missleading)

[BladeOne/lib/BladeOne.php](https://github.com/EFTEC/BladeOne/blob/b912e9f060aaa999c0ac2fcf4b40f7a8e6cd66c0/lib/BladeOne.php#L1096)

**Comment by jorgecc** [comment]
done in 4.8
