### ISSUE TITLE
Foreach loop with variable containing "as"

### ISSUE THREAD

**Issue by SergeyZubov** [EFTEC/BladeOne#17]
Hi. First of all - great job on single Blade class.

Today had an issue with `foreach` loop when tried to loop through variable named `$cancelReasons`.
Checked out compiled file and noticed that something strange was with `foreach`.
As my variable contained `as` string then `compileForeach()` function using `preg_match('/\( *(.*) *as *([^\)]*)/', $expression, $matches);` split incorrectly `@foreach ($cancelReasons as $code => $reason)` part.

Don't know if this is correct way to fix it but changing `preg_match` part to `preg_match('/\( *(.*) * as *([^\)]*)/', $expression, $matches);` (added space between `* as`) helped solve my issue.

Maybe there is better way solving this or at least this could help someone.

**Comment by jorgecc** [comment]
Im not fancy of using regular expression.  This part of the code comes directly from Laravel, so may be they get it bad too.
I added this fix.
