### ISSUE TITLE
Operation not defined:@return

### ISSUE THREAD

**Issue by nhuebnereagle** [EFTEC/BladeOne#19]
First! Thank you so much for making this functional :) 

Sorry to report this, but it looks like "function compileStatements" is picking up @return tags which are created in PHP Comments.

Here's some code from the blade file. I am going to try to prevent this error from continuing, but if you have a way to fix / workaround correctly, please let me know.

Thank you!

`Operation not defined:@return`

```
    <script>
        /**
         * Advanced calling object. You can specify custom functions to run at various
         * points in the form submission process.
         */
        var test = {
            /**
             * An example function that is run right before form is submitted via AJAX.
             * @return  void
             */
            beforeSubmit: function ()
            {
                $.vine.log('Form is about to be submitted.');
            },
```

**Comment by jorgecc** [comment]
I am not tested but

https://stackoverflow.com/questions/20603554/how-to-include-symbol-in-blade-template-page-without-it-being-processed-as-bla

Also:

> kevinbacon{!!'@'!!}gmail.com

It renders kevinbacon@gmail.com

Tested, it works.

**Comment by nhuebnereagle** [comment]
Perhaps you should just silently ignore any @ tags that do not match valid @ tags. This would prevent it from tripping on these.

**Comment by jorgecc** [comment]
Its too prone to error.  Plus , the library allows to add new classes so it could be a messes with code working and others not because somebody already defined the class.
