### ISSUE TITLE
BladeOneLogic: Syntax Error using switches

### ISSUE THREAD

**Issue by Papagaai35** [EFTEC/BladeOne#2]
The following code:

``` blade
@switch($countrySelected)
    @case(1)
        first country selected<br>
    @case(2)
        second country selected<br>
    @defaultcase()
        other country selected<br>
@endswitch()
```

with

``` php
use eftec\bladeone\BladeOne;
use eftec\bladeone\BladeOneHtml;
use eftec\bladeone\BladeOneLogic;;

class Blade extends BladeOne{
    use BladeOneLogic;
}
$blade = new Blade("/var/www/views","/var/www/tmp");
$blade->run("view")
```

retults in the following error:
**Parse error**: syntax error, unexpected ' ', expecting case (T_CASE) or default (T_DEFAULT) or '}' in **/var/www/tmp/test _a94a8fe5ccb19ba61c4c0873d391e987982fbbd3** on line **2**

**Comment by Johntaa** [comment]
delete the white space between @switch and the first @case
http://stackoverflow.com/a/28458649
