### ISSUE TITLE
@parent should be put back in

### ISSUE THREAD

**Issue by nhuebnereagle** [EFTEC/BladeOne#20]
`@parent`  Show the original code of the section | REMOVED(*)

Unless there's a better way to handle this, here's an example of `@parent` and why it's needed:

 - A template contains a JS blade file used for general functions
```
@section('js_bottom')
<script>
alert('Template JS');
</script>
@endsection
```

 - A resource view for handling a form post (creating a new user for example):
```
@section('js_bottom')
<script>
alert('form post js code');
</script>
@endsection('js_bottom')
```

`When you overwrite the section, you lose one of the sections. From what I can tell, the first one sticks, the rest do not`.

If you were to add @parent back, the second one could "STACK" to the first, like so, giving you both alerts:
```
@section('js_bottom')
@parent
<script>
alert('form post js code');
</script>
@endsection('js_bottom')
```

**Comment by jorgecc** [comment]
Let's me check it.   Im not really convinced how it works. But i am sticking with the original definition of Laravel's Blade.

**Comment by nhuebnereagle** [comment]
Yeh I use @parent in Laravel so when I tried it and it didn't work I was wondering how I was supposed to append sections to each other.

Here's the Laravel 5.5 Docs:
https://laravel.com/docs/5.5/blade

It shows it's still in use. 

Basically, the first section created "sidebar" should be overwritten by any other "sidebar" sections created consecutively, however, if you add @parent to each consecutive section "sidebar" they should stack together to output all of them.

```
@section('sidebar')
    @parent

    <p>This is appended to the master sidebar.</p>
@endsection
```

**Comment by jorgecc** [comment]
Done in 2.1
