### ISSUE TITLE
PHP 8.4 Deprecated Warning: Nullable Parameter

### ISSUE THREAD

**Issue by satopian** [EFTEC/BladeOne#202]
Thank you for this great library.

In PHP 8.4, I encountered the following warnings.

> PHP Deprecated:  eftec\bladeone\BladeOne::last(): Implicitly marking parameter $callback as nullable is deprecated, the explicit nullable type must be used instead in C:\foo\bar\lib\BladeOne.php on line 1101

> PHP Deprecated:  eftec\bladeone\BladeOne::first(): Implicitly marking parameter $callback as nullable is deprecated, the explicit nullable type must be used instead in C:\foo\bar\lib\BladeOne.php on line 1128

`public static function last($array, ?callable $callback = null, $default = null)`
Using ?callable eliminates the Deprecated warning.

**Comment by mark-addams001881** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the last() and first() methods in the BladeOne class to use explicit nullable type (?callable) for the $callback parameter to address PHP 8.4 deprecation warnings.

You can review changes in this commit: https://github.com/mark-addams001881/EFTEC-BladeOne-202/commit/eca3f7ace5619ddb65ce93474bd93b6f78b9031e.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by satopian** [comment]
The issue does not occur in v4.17.1 so I will close the issue.
Thank you.
