### ISSUE TITLE
@parent - New issue

### ISSUE THREAD

**Issue by nhuebnereagle** [EFTEC/BladeOne#21]
After using the @parent update you previously pushed, I am now seeing this echo at the end of my DOM document:

`@parentXYZABC`

**Comment by jorgecc** [comment]
Do you have some example of it?
Are you closing the section?

**Comment by nhuebnereagle** [comment]
Yes, right now I'm only using it for one blade file:

```
@section('js_bottom')
@parent
    @include('widgets.ckeditor', ['textarea_id' => 'information'])
@endsection
```

I have no other @section('js_bottom') anywhere else at the moment.

**Comment by nhuebnereagle** [comment]
Just so you know, I did test the @parent, and the updates you put in worked. But this weird @parentXYZABC showing up at the end of the document is the only weird thing happening.

You should be able to reproduce it - let me know if I need to send you anything else.

**Comment by jorgecc** [comment]
In the extends layout, are you  @yield('js_bottom') ?

**Comment by nhuebnereagle** [comment]
Yes

**Comment by jorgecc** [comment]
A yield section is a content-less section, so @parent shouldn't do nothing.

I changed the code, so @parent shows the default value of @yield, example : 
-- template1
@section('code')
@parent   parent will show 'default', if not default then it will show nothing.
@endsection

-- template2
@yield('code','default')

**Comment by nhuebnereagle** [comment]
That fixed it - Thanks man! Great job :)
