### ISSUE TITLE
[enhancement] pass data / vars to @yield for sections

### ISSUE THREAD

**Issue by serjoscha87** [EFTEC/BladeOne#23]
I need some tiny component-like views which only contain a few lines of code but are fed with dynamic data from a database - in concrete I need two nested divs with a button that has a dynamic data-attribute. **I don't want to create a file for this few lines of code** because things will get messy quite quick as the amount of tiny code snippets grow. I know that I could use @include or @component in order to load a view from a file but that's just **not what I want**. Would it be possible to enable the @yield method to pass data to a section in order to do something like this:

```html
@section('generic_popup_button_markup')
<div class="generic_action_buttons">
    <button class="btn btn-mutateable generic-show-location-on-map-btn" data-marker="{{$popup_id}}">Show location on map</button>
    <button class="btn btn-mutateable">Get in touch for this Object</button>
</div>
@endsection
<!-- some more code and stuff -->
@yield('test', ['popup_id' => $some_db_md5_record])
```

these buttons/markup is used in several different places and I don't like the thought to do changes to their markup in all sports as soon as it changes

**Comment by jorgecc** [comment]
im short of time this moth but i will try to check it.

**Comment by serjoscha87** [comment]
thank you very much, that would be awesome!

**Comment by jorgecc** [comment]
Sheesh, hard month... :-(
I evaluated it and it doesn't feel right.  Plus, the code is evaluated from up to down so it will not work (there are some exceptions about it).

Anyways, it's possible to use push and stack, with the sole difference is, if you push more than one element then it will stack.

```
@section('generic_popup_button_markup')
<div class="generic_action_buttons">
    <button class="btn btn-mutateable generic-show-location-on-map-btn" data-marker="**@stack('elem')**">Show location on map</button>
    <button class="btn btn-mutateable">Get in touch for this Object</button>
</div>
@endsection
<!-- some more code and stuff -->
**@push('elem')$some_db_md5_record@endpush**
```

**Comment by serjoscha87** [comment]
thank you!
