### ISSUE TITLE
Class eftec\bladeone\BladeOne does not exist

### ISSUE THREAD

**Issue by ankitce** [EFTEC/BladeOne#28]
The usage as mentioned under  "using composer's autoload.php" is not working.
I am always getting error 

> Class eftec\bladeone\BladeOne does not exist

I've installed the package via composer. However, it works when I directly include the BladeOne.php file.

**Comment by jorgecc** [comment]
I should check it but I don't use Composer at all because it's a chore.  Nothing beats xcopy.

I use:
use eftec\bladeone;

$blade=new bladeone\BladeOne($views,$compiledFolder);

**Comment by sourcegr** [comment]
so have you checked it? Because it is still there...

**Comment by jorgecc** [comment]
You could check this one

https://github.com/EFTEC/BladeOne/blob/master/examples/testComposer.php
