### ISSUE TITLE
verbatim not work, maybe is a bug

### ISSUE THREAD

**Issue by sanderswang** [EFTEC/BladeOne#29]
i use @verbatim as:

```
@verbatim
    sssssssss
@endverbatim
```

got: 
```
BladeOne Error [@compile]:
Operation not defined:@__verbatim__
````
![tim 20180422193037](https://user-images.githubusercontent.com/154830/39094541-b56279da-4663-11e8-9888-938ff93340f8.png)

**Comment by jorgecc** [comment]
Done. 2.3.1
