### ISSUE TITLE
Suggestion about cache filenames

### ISSUE THREAD

**Issue by ilyachase** [EFTEC/BladeOne#35]
Why do we need cache filename in format `$fileName . ' _' . sha1($fileName)` ?
1. Space in filename may cause problems when you will try to use it in CLI.
2. `sha1($fileName)` seems redundant because semantically it's the same with `$fileName` (same filename will always result in same hash).

I rewrote it to just `$fileName . '.php'` (because it's basically a regular php files) in my project and it seemed more straightforward.

**Comment by jorgecc** [comment]
3.3 fixed.
