### ISSUE TITLE
setMode( $mode ) for BladeOne

### ISSUE THREAD

**Issue by ilyachase** [EFTEC/BladeOne#36]
I understand that global variables are useful when you distinct dev and prod configurations (for example, you're passing constants from `.env` files), but constants are defined once and kept the same for whole run time. For example, if you want to compile some of templates in one mode, and some in another, you will not able to.

If we had some sort of `setMode( $mode )` that will prevail over constant if used, it would be more flexible.

**Comment by ilyachase** [comment]
Also I can contribute it in PR if you're agree.

**Comment by jorgecc** [comment]
What do you mean PR? If you mean Public Relation, then **I'm looking for one** but not for this project, this project is a toy.

I hate to use global variables but it's how PHP usually works but I will check about this matter. Since BladeOne is not a static class then it makes sense.

**Comment by ilyachase** [comment]
I mean Pull request.

**Comment by jorgecc** [comment]
3.3 fixed.
I added a setMode, a constant and a new parameter in the constructor.
