### ISSUE TITLE
@auth @endauth

### ISSUE THREAD

**Issue by ar3s** [EFTEC/BladeOne#41]
Hi,
I'm looking testsecurity.php but I can't understand much.
How can I let blade know i'm authenticated or not? How does it work with bladelang?

thanks,
A.

**Comment by jorgecc** [comment]
This library is a template system; it's not a security system.  So you must implement your own security or use an existent one.

I explain.
Let's say that you are a user called ar3s, and you have permissions of read and write.

Then you must add the next code before running the template

$blade->setAuth("ar3s","user",['read','write']);

**Comment by ar3s** [comment]
I've got it!
thank you very much :) 👍
