### ISSUE TITLE
Make compiled files deterministic

### ISSUE THREAD

**Issue by qurben** [EFTEC/BladeOne#44]
Thanks for this project, I like how lightweight and straightforward it is. 

I am currently using BladeOne to compile templates, which are then sent to a production server, which runs in `BladeOne::MODE_FAST`. This setup uses git to make sure that only changed files get updated. 

The current implementation of BladeOne uses `uniqid` in the extends implementation. This causes each run of `compile`/`run` to result in a different file. Which in my case causes the file to be unnecessarily updated on my production server.

Would it be possible for `compileExtends` to behave in such a way that it always returns the same output for the same input?

**Comment by bassauer-storms-media** [comment]
and another thing (not directly according to this issue): I liked it better (for debugging) as the blade file name was also written to the compiled file name instead of just that hash now

**Comment by jorgecc** [comment]
Fixed on 3.6
