### ISSUE TITLE
Unable to load Blade v 3.5 and next

### ISSUE THREAD

**Issue by ar3s** [EFTEC/BladeOne#47]
Hi,
I've updated from version 3.4 to version 3.7 without change nothing and the plugin won't load anymore. I'm using BladeWithLang. I've also try to downgrade to version 3.5 and the problem still persist. Version 3.4 is okay.

I'm delegating to Composer autoload the loading.  So my situation is the following:

**config.php file:**

> require_once ('../vendor/autoload.php');

**MyBladeLang.class.php file:**

> use eftec\bladeone;
> use eftec\bladeone\BladeOneLang;
>
> class MyBladeLang extends bladeone\BladeOne {
>   use BladeOneLang;
> }

**index.php file:**

> $blade  = new \MyBladeLang($source, $cache, MyBladeLang::MODE_SLOW);

Since 3.4 this was working correctly. Can you explain me what am I doing wrong that stopped to load the class?

Thanks in advance,
Best Regards,

**Comment by jorgecc** [comment]
`<?php
require_once ('vendor/autoload.php');

use eftec\bladeone;
use eftec\bladeone\BladeOneLang;

class MyBladeLang extends bladeone\BladeOne {
    use BladeOneLang;
}
$views = __DIR__ . '/views';
$compiledFolder = __DIR__ . '/compiled';


$blade = new \MyBladeLang($views, $compiledFolder, MyBladeLang::MODE_SLOW);

$lang='jp'; // try es,jp or fr
include __DIR__.'/lang/'.$lang.'.php';


try {
    echo $blade->run("Lang.test",array('var'=>'1'));
} catch (Exception $e) {
    echo "error found ".$e->getMessage()."<br>".$e->getTraceAsString();
}
`

tree
├───compiled
├───lang
├───vendor
│   ├───composer
│   └───eftec
│       └───bladeone
│           └───lib
└───views
    └───Lang

**Comment by jorgecc** [comment]
`{
    "name": "jorge/dummy",
    "type": "project",
    "require": {
        "eftec/bladeone": "^3.7"
    },
    "authors": [
        {
            "name": "Jorge Castro",
            "email": "jorge.castro.c@gmail.com"
        }
    ]
}
`

**Comment by jorgecc** [comment]
I tried a  new project (the project explained in the code) and it works.  I mentioned about the "dir" because of the markdown annotation removes the _ _ character.

Which version of PHP are you using?  and, how its fail?
ps: remember to update composer and the autoinclude.

**Comment by ar3s** [comment]
This is the error i receive from **my** autoload class which loads the MyBladeLang class:

**Unable to load the class: Blade (errro code: 2) require (Blade.php): failed to open stream: No such file or directory**

anyway I can't understand why in 3.4 and older works and 3.5 and newer dont.

**Comment by jorgecc** [comment]
Where are you trying to load the class name "Blade"?.
If the class blade exists, then bladeone will try to load it as a namespace class.

**Comment by ar3s** [comment]
I'm not loading it directly. I'm loading everything with 2 autoloaders. One is mine and loads my classes and the other one is composer autoload. Basically what I can see is that after MyBladeLang class is loaded by mine autoloader another class  Blade (blade.php) tries to load and here it fails. I've look inside blade php and I've noticed a lot has chanced from 3.4 to 3.5

**Comment by ar3s** [comment]
Hi,
just to inform you I have **solved** the problem.
I have excluded the Blade class to be loaded automatically and now it works correctly. :)
Sorry for the long troubleshooting. Keep up the great job! 👍

**Comment by jorgecc** [comment]
I am planning to remove Blade class anyways.
I added it because we could use the library as a static Blade::operation(). However, the idea is silly (even when Laravel uses it), why?.
* Blade should be in the namespace root.
* The target of BladeOne is to create a single-class file (excepting extensions).
* global is less than elegant but it works and it's less bloated.
* And using static call is only syntax sugar.

[https://github.com/EFTEC/BladeOne/releases/tag/3.8](3.8)
