### ISSUE TITLE
Support for Markdown

### ISSUE THREAD

**Issue by xy2z** [EFTEC/BladeOne#55]
Any ideas on supporting Markdown?

In Laravel we can install a package like https://github.com/andreasindal/laravel-markdown
but I don't think this would work for BladeOne

**Comment by qurben** [comment]
laravel-markdown is a thin wrapper around the parsedown package.

To do the same thing in BladeOne you can use the following trait:

```php
trait BladeOneDown {
    private $capturing = false;
    
    public function compileMarkdown($expression) {
        if ($expression == NULL) {
            $this->capturing = true;
            return "<?php ob_start(); ?>";
        }
        return "<?php echo (new \Parsedown())->text$expression; ?>";
    }

    public function compileEndMarkdown() {
        if (!$this->capturing) throw new \Exception("@endmarkdown without @markdown");

        $this->capturing = false;

        return "<?php echo (new \Parsedown())->text(ob_get_clean()); ?>";
    }
}
```

Make sure that Parsedown is installed with:  (in your shell)
```
composer require erusev/parsedown
```

Use it by subclassing `BladeOne` with this trait.

```php
class MyBladeOne extends BladeOne {
    use BladeOneDown;
}
```

```php
$blade = new MyBladeOne($viewPath, $compiledPath);

echo $this->blade->runString(
            <<<'BLADE'
@markdown
# This is some markdown

A paragraph `code` _cursive_.
@endmarkdown

@markdown($md)
BLADE
, ['md' => "# Title \n Some _text_"]);
```

**Comment by qurben** [comment]
The autodiscovery from laravel-markdown is Laravel specific and currently not implemented in any way in BladeOne.

**Comment by xy2z** [comment]
Thanks, works great :)

So this wont be implemented in BladeOne?

**Comment by qurben** [comment]
That's not something I can say @jorgecc will be available next week. But from what I saw in the previous development is that they are trying to keep BladeOne lightweight.

**Comment by jorgecc** [comment]
Hi there

you are using the wrong library, you should use the vanilla original library 

[erusev/parsedown](https://github.com/erusev/parsedown)

Auto-discovery is a feature of Laravel, and if you are using this library, then you don't want the mumbo jumbo of Laravel (I am over-dramatizing, I admit it).  It's the reason why this library exists.
```

trait BladeOneDown {
    private $capturing = false;
    private $parseDown;    
    public function compileMarkdown($expression) {
      if ($this->parseDown===null) {
              $Parsedown = new Parsedown(); // who needs auto-discovery when you could load on request.
      }
        if ($expression == NULL) {
            $this->capturing = true;
            return "<?php ob_start(); ?>";
        }
        return "<?php echo \$this->parseDown->text$expression; ?>";
    }

    public function compileEndMarkdown() {
        if (!$this->capturing) throw new \Exception("@endmarkdown without @markdown");

        $this->capturing = false;

        return "<?php echo \$this->parseDown->text(ob_get_clean()); ?>";
    }
}
```
