### ISSUE TITLE
CSS Media Queries conflict

### ISSUE THREAD

**Issue by VCardWEb** [EFTEC/BladeOne#58]
I'm using responsive email's the CSS is direct in `<head>` the problem I have is that:
`@media [whatever] { /* CSS... */ }`
So every time I try to send an html email it returns compile error because the @media is not defined... s, in order to "fix it" I had to remove my CSS media queries... but my emails doesn't look "responsive"...

**Comment by jorgecc** [comment]
You must escape the symbol "@"  Try @@media

It's also valid if you want to use an email, for example, contact@page.com it must be written as contact@@page.com

**Comment by VCardWEb** [comment]
I see, never had that problem before so I never escape/used @@, not even with Laravel, every day we learn something new, Thank you.

**Comment by jorgecc** [comment]
Ok, it is different.   Since Laravel support, then a) Laravel has a whitelist of @ items or it only processes commands if they are in a list.

**Comment by Sepremex** [comment]
I was using Philo's version of blade, never had a problem, but what I don't like about that version is that it has lots of other libraries, libraries that I have never use... 
I like this version that now is my #1 Blade version.
What is missing is a Router class, like Laravel Router, or even an standalone version of Laravel Router... but that is another story... Thank you for this version of Blade!

**Comment by jorgecc** [comment]
About route, I do it manually following the standard way used by asp.net MVC ([module]/controller/method/id1/id2) because of performance issues (one of the reasons why Laravel is not suitable for some projects).
