### ISSUE TITLE
Add BladeOne to my Wordpress theme

### ISSUE THREAD

**Issue by kezern** [EFTEC/BladeOne#59]
Is it possible to add Bladeone to the wordpress theme I'm developing?
I have installed it using composer and now I have vendor folder in my theme. I have added 

`require get_stylesheet_directory().'/vendor/autoload';`

And I'm trying to add in a shortcode 

```
Use eftec\bladeone;
$views = __DIR__ . '/views';
$cache = __DIR__ . '/cache';
$blade=new bladeone\BladeOne($views,$cache,BladeOne::MODE_AUTO);
echo $blade->run("hello",array("variable1"=>"value1"));
```

I'm getting an error in the Use line 
`Parse error: syntax error, unexpected 'Use' (T_USE)`

**Comment by jorgecc** [comment]
Use must be at the top of the code.  Where are you adding this code?  (in which file?)

**Comment by kezern** [comment]
I'm adding it at the top of functions.php
This is my code

```
require_once get_stylesheet_directory().'/vendor/autoload.php';
use eftec\bladeone;

function test_shortcode_function() {
    $views = get_stylesheet_directory() . '/views';
	$cache = get_stylesheet_directory() . '/cache';

	$blade=new bladeone\BladeOne($views,$cache,BladeOne::MODE_AUTO);
	echo $blade->run("hello",array("variable1"=>"value1"));
}
add_shortcode('test_shortcode','test_shortcode_function');
```

And in wordpress log I can see this output

`[01-Nov-2018 17:30:25 UTC] PHP Fatal error:  Uncaught Error: Class 'eftec\bladeone' not found in /home/***********/public_html/wp-content/themes/theme-child/functions.php:11`

**Comment by jorgecc** [comment]
```
require_once get_stylesheet_directory().'/vendor/eftec/BladeOne/BladeOne.php';
// require_once get_stylesheet_directory().'/vendor/autoload.php'; // we aren't using this one.
//use eftec\bladeone;

function test_shortcode_function() {
    $views = get_stylesheet_directory() . '/views';
	$cache = get_stylesheet_directory() . '/cache';

	$blade=new \eftec\bladeone\bladeone\BladeOne($views,$cache,\eftec\bladeone\BladeOne::MODE_AUTO);
	echo $blade->run("hello",array("variable1"=>"value1"));
}
add_shortcode('test_shortcode','test_shortcode_function');
````

**Comment by kezern** [comment]
Hi jorgecc,
Same error, class not found

**Comment by jorgecc** [comment]
Oops, a typo. It is \eftec\bladeone\BladeOne and not \eftec\bladeone\BladeOne\BladeOne.  Edited the last answer with it.

**Comment by kezern** [comment]
Same error.
Is it possible vendor path has also a typo? I have browser thrown it and I think it is
`require_once get_stylesheet_directory().'/vendor/eftec/bladeone/lib/BladeOne.php';`

But it still doesn't work

**Comment by jorgecc** [comment]
Ok, the require_once is right (because php is not generating an error) but it's unable find the class because the namespace

Can you try to edit BladeOne.php and remove this line:  
```
namespace eftec\bladeone;
```

And try with this line:
```
	$blade=new BladeOne($views,$cache,BladeOne::MODE_AUTO);
```

**Comment by kezern** [comment]
Removing the namespace worksfine.
I had to change also the require becase it was returning error.
require_once get_stylesheet_directory().'/vendor/eftec/bladeone/lib/BladeOne.php';

Thankyou very much!!!

**Comment by jorgecc** [comment]
However, it is only a test.  I suggest you, to add the namespace back to BladeOne.php because you could miss futures updates (I added a new version today).

It must be the correct line (maybe something is wrong about it).

> $blade=new \eftec\bladeone\BladeOne($views,$cache,\eftec\bladeone\BladeOne::MODE_DEBUG);
