### ISSUE TITLE
How get baseUrl with bladeone?

### ISSUE THREAD

**Issue by ssheduardo** [EFTEC/BladeOne#6]
Hi,
You class BladeOne is amazing, but I have a question, how get baseurl through of a helper?
Twig for slim have the method called baseUrl(), how implement same helper?
example: [link](https://github.com/slimphp/Slim-Views)
Best regards

**Comment by jorgecc** [comment]
May be i will add those functions to the definitions
However, right now you can call any function as follow
{{VisualHelper::baseUrl()}}

Where VisualHelper is the class where your function is stored and baseUrl is the (static) functions.  Right now i awake a bit dumb so i don't remember how to implement it ($_SERVER or something like that)

`class VisualHelper {

public static function baseUrl() {
    return "something";
}
}`

**Comment by ssheduardo** [comment]
Gracias por la respuesta,
Sería bueno el implementarlo de forma nativa, lo que no se si por ahí vi que se puede usar share en blade, algo así
https://laravel.com/docs/5.3/views#sharing-data-with-all-views

De todas formas tratare con tu solución y estaré atento a nuevas actualizaciones.
