### ISSUE TITLE
Error writing and accessing on windows server

### ISSUE THREAD

**Issue by koltejas** [EFTEC/BladeOne#61]

**Comment by jorgecc** [comment]
You should check if the user of the application pool has permission (usually it is the user IUSR_*) to access and write the folder \views and \compiles (or the name of the folders that you are using.

**Comment by koltejas** [comment]
The problem seems to be of '/' as the website is hosted on windows server. 

mode: BladeOne::MODE_DEBUG
BladeOne Error [Compiling]:
Unable to save the file [C:\Inetpub\vhosts\packexindia.com\httpdocs\demo/compiles/dates.bladec]. Check the compile folder is defined and has the right permission

mode: BladeOne::MODE_FAST
Warning: include(C:\Inetpub\vhosts\packexindia.com\httpdocs\demo/compiles/c09a2565eb3e551d0b33b3f5111b7fd0b90263f4.bladec): failed to open stream: No such file or directory in C:\Inetpub\vhosts\packexindia.com\httpdocs\demo\vendor\eftec\bladeone\lib\BladeOne.php on line 2110

Though bladeone works perfectly on my local apache server. Is there a workaround for this?

**Comment by jorgecc** [comment]
PHP and windows work perfectly with the path separator "/" and "\" (unless you are using a old version of php

Can you check if you have permission?

Write this file (in the root of the project) test.php

```
<?php
$handle = fopen("testing.txt", "w");
fclose($handle);
```
