### ISSUE TITLE
compiling empty template causing error

### ISSUE THREAD

**Issue by Elevioux** [EFTEC/BladeOne#70]
`$ok = @file_put_contents($compiled, $optimizedContent);
                if (!$ok) {
                    $this->showError("Compiling", "Unable to save the file [{$compiled}]. Check the compile folder is defined and has the right permission");
                    return false;
                }`

file_put_contents returns the number of bytes that were written to the file, or FALSE on failure.

So, here should use $ok===false. In BladeOne.php Line 404.

**Comment by jorgecc** [comment]
done
