### ISSUE TITLE
CSRF token

### ISSUE THREAD

**Issue by RealMaurge** [EFTEC/BladeOne#73]
The CSRF token field will not refreshed with a new value in the compiled view. Even when mode is set to MODE_SLOW

**Comment by jorgecc** [comment]
Ok, let's me check this one.

**Comment by jorgecc** [comment]
`$isvalid=$blade->csrfIsValid();   `

* This function generates the token (if it's called via GET) and returns true.
*  or it validates the token (if it's called via POST) and returns true if the token is valid.

You can obtain the token using the method: 
` $blade->csrf_token;`

And you can generate a new token using the method:
`$blade->regenerateToken()`  
This method is optional, Usually you won't re-generate a token per call (but it's up to you). Why? Explanation:

https://security.stackexchange.com/questions/22903/why-refresh-csrf-token-per-form-request
