### ISSUE TITLE
foreach not use as object same example

### ISSUE THREAD

**Issue by hoangnamitc** [EFTEC/BladeOne#74]
Hi,

I'm push 1 array from PHP via bladeOne.

I foreach it,

`
@foreach ($array as $item)

    {{ $item->id }} (not working)

    {{ $item['id'] }} (working)

@endforeach
`

Why?

Thanks!

**Comment by jorgecc** [comment]
It is because you are not parsing an array of object but an array of arrays

# Array objects
```
$obj=new stdClass();
$obj->id=1;
$obj->name="john";
$arrObject=[$obj,$obj];
```
```
@foreach($arrayobjects as $item)
    item:{{$item->id}} {{$item->name}}<br>
@endforeach
```

# Array of arrays
```
$arr=['id'=>1,'name'=>'John'];
$arrays=[$arr,$arr];
```

```
@foreach($arr as $item)
    item:{{$item['id']}} {{$item['name']}}<br>
@endforeach
```
