### ISSUE TITLE
Feature Request: @pushonce directive

### ISSUE THREAD

**Issue by iAdesanyaDaniel** [EFTEC/BladeOne#76]
Good day Team,

It's really a nice work been done here. This extension has really been helpful in my Codeigniter projects.

I just want to keep a tab on this Feature Request, and this [link to an SO post](https://stackoverflow.com/questions/38135455/how-to-have-one-time-push-in-laravel-blade)

I'm willing to develop this feature, when I'm free, but I would really appreciate any brief explanation on how to go about it.

Thank you.

**Comment by jorgecc** [comment]
ok, let's me check it.

**Comment by jorgecc** [comment]
#75 addes method @pushonce('namestack') and @endpuchonce
