### ISSUE TITLE
Indent turns into a single space after compile

### ISSUE THREAD

**Issue by rugaard** [EFTEC/BladeOne#77]
I'm currently compiling a `.blade.php` but when I'm compiling it, the indent is being replaced with a single space.

Original `.blade.php` before compile:
```docker
# Install Node.js & Yarn
RUN curl --silent --location https://rpm.nodesource.com/setup_11.x | bash - && \
    curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | tee /etc/yum.repos.d/yarn.repo && \
    yum install -y yarn
```
Result of compile:
```docker
# Install Node.js & Yarn
RUN curl --silent --location https://rpm.nodesource.com/setup_11.x | bash - && \
 curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | tee /etc/yum.repos.d/yarn.repo && \
 yum install -y yarn
```

For me, which are using `.blade.php` templates as stub files to create misc. auto-generated files, it's going to cause a lot of problems. Especially with YAML files, when relies on correct indentation.

**Comment by jorgecc** [comment]
Done.

You could use the new method setOptimize(false) to avoid to remove tabs.
Also, you could use the method setIsCompiled(false) to avoid to generate the compiled file.

```php
$blade=new BladeOne(null,null,BladeOne::MODE_DEBUG);
$blade->setOptimize(false); // the result is not optimized (it will not remove tabs of multiple spaces)
$blade->setIsCompiled(false); // the result is not compiled on a file.
```

**Comment by rugaard** [comment]
That's probably the fast fixed issue I've ever experienced on GitHub.

Thank you, sir! 👏🏻
