### ISSUE TITLE
Possible to disable dot annotations in template path?

### ISSUE THREAD

**Issue by rugaard** [EFTEC/BladeOne#78]
I'm back again. But this time it's more a feature request than an actual bug.

Like I mentioned in my previous issue, I'm currently working on a CLI tool, where I'm using `BladeOne` as the template engine to auto-generate misc. files. Works perfectly!

But, I've stumpled upon a little annoying thing. Since all my stub files ends with `*.stub` the IDE editors won't recognize each type of file. A stub file is either be a `Dockerfile`, `.conf` or even a `.yaml`.

There fore I've added the original extension to the filenames. For example:
- `Dockerfile.docker.stub`
- `nginx.conf.stub`
- `buildspec.yaml.stub`

I've used Blade One's `setFileExtension` to set `.stub` as the template extension, so it treats all the  `*.stub` as "Blade" templates.

BUT when I'm trying to compile these templates, the dots in the template paths is automatically being replaced with `/` (which obvs. is correct):
```
# My template path -> Blade One's converted template path.

templates/config/nginx.conf.stub -> templates/config/nginx/conf.stub
```

Therefore I was wondering, if it would make sense (or even possible) to be able to disable this "dot" annotation in the template paths?

**Comment by rugaard** [comment]
Or maybe instead of disabling the dot annotation in template path, you could maybe support an array of file extensions?

This way I would be able to add them all like:
```
$bladeOne->setFileExtension([
    '.blade.php',
    '.docker.sub',
    '.nginx.conf.stub',
    '.buildspec.yaml.stub'
])
```

That would actually be super cool and super useful :)

**Comment by jorgecc** [comment]
Hi: 

The system calls the template using the command 

```php
echo $blade->run("Test.hello",[]);
```
Where the template is read in the folder (view)/Test/hello.blade.php (or the extension used).  It is syntax sugar and sometimes it's not clear.

Now, this function also works with literal filenames.

```php
echo $blade->run("Test/hello.blade.php",[]);
```
if the template file has "/", then it is considered literal and it is not parsed or converts the dot as "/"

**Comment by rugaard** [comment]
I'm sorry, but that's what I'm doing at it doesn't work.

This is what I'm doing:
```php
$blade->run('Laravel/Docker/Application/dockerfile.docker.stub', []);
```
And that results in the following error:
```
File does not exist at path /project/Stubs/Laravel/Docker/Application/dockerfile/docker/stub.stub
```

As you can see, it still takes the second to last `.` and converts it to a `/` and for some reason it also always append the `fileExtension` to the filename, resulting in a `.stub.stub`.

This is not how Laravel's Blade works as far as I remember :)
