### ISSUE TITLE
Caching doesn't work when directory doesn't exist

### ISSUE THREAD

**Issue by m-mohr** [EFTEC/BladeOne#8]
Caching doesn't work when the caching directory doesn't exist, the templating engine can't save the file as file_put_contents fails.

This could be fixed by adding something like:
```
                $dir = dirname($compiled);
                if (!file_exists($dir)) {
                    $ok = @mkdir($dir, 0777, true);
                    if (!$ok) {
                        $this->showError("Compiling","Unable to create the compile folder [{$dir}]. Check the permissions of it's parent folder.", true);
                    }
                }
```
before:
```
                $ok = @file_put_contents($compiled, $contents);
```
in method compile().

For me this is neccesary as I have a software where you can install different themes and the caching directory is therefore flexible (cache/templates/<template-name>).

**Comment by CallumCarmicheal** [comment]
Shouldn't you catch the mkdir exception in the event that PHP does not have permissions to create the directory and show an exception instead of just suppressing it. In the event that there are no permissions to the caching directory this would allow for a fallback instead of just another exception waiting.

**Comment by m-mohr** [comment]
Sounds like good idea, yes. I changed it accordingly above and in PR #10 .

In generel it might be a better idea to replace calls to showError with proper exceptions. In the doc it even says `@throws Exception`, but none is thrown, but the proprietary and ugly showError is used.

**Comment by jorgecc** [comment]
pulled

**Comment by m-mohr** [comment]
Improved the above with PR #14 .
