### ISSUE TITLE
Can we have stripParentheses and stripQuotes as public methods?

### ISSUE THREAD

**Issue by bassauer-storms-media** [EFTEC/BladeOne#84]
for most custom directives I sometimes use these both methods so it would be nice if they were public instead of protected

**Comment by jakewhiteley** [comment]
I will submit a PR.

TBH I believe `stripParentheses` should be run on all expressions regardless. I find it very annoying having to do it myself or rework my directives because of it.

**Comment by jorgecc** [comment]
done. #3.28

**Comment by jakewhiteley** [comment]
@jorgecc Do you not think that `stripParentheses` should be run by default for custom directives?

In real terms, I can't really think of a time that I want my args coming through inside ().

I was thinking something as simple as:

````php
#replace the following:
$match[0] = call_user_func($this->customDirectives[$match[1]], static::get($match, 3));

# with
$match[0] = \call_user_func(
    $this->customDirectives[$match[1]],
    $this->stripParentheses(static::get($match, 3))
);
````

on line #704.
