### ISSUE TITLE
supporting sessions ?

### ISSUE THREAD

**Issue by jhayann** [EFTEC/BladeOne#88]
how can i access session variables ?

**Comment by jorgecc** [comment]
You can but conceptually it's not right to do in the view layer, so you could do:

## 1

In the view (*.blade.php) file:

```php
{{$_SESSION["mysession"}}
```

## 2 (recommended)

or in the controller file (.php file)

```php

$blade = new bladeone\BladeOne();
echo $blade->run("hello",array("mysession"=>$_SESSION['mysession']));
```

then in the template hello.blade.php

```php
{{$mysession}}
```
