### ISSUE TITLE
set own function dont work

### ISSUE THREAD

**Issue by jhayann** [EFTEC/BladeOne#90]
`protected function compileMyFunction($expression)
{
    return $this->phpTag . "echo 'YAY MY FUNCTION IS WORKING'; ?>";
}`

**Comment by jorgecc** [comment]
This function must be added inside a class and this class must extend the class BladeOne.

Example:

https://github.com/EFTEC/BladeOne/blob/master/examples/testcustom2.php

And it uses the next view 

https://github.com/EFTEC/BladeOne/blob/master/examples/views/TestCustom/test2.blade.php
