### ISSUE TITLE
Can't include view file if the section is undefined

### ISSUE THREAD

**Issue by lexdubyna** [EFTEC/BladeOne#91]
In the Laravel docs there is this code:
`@yield('content', View::make('view.name'))` - `value will be rendered if the section being yielded is undefined`
Are there any implementations of this functionality in BladeOne?
BTW, thanks for awesome package!

**Comment by jorgecc** [comment]
Hi:

https://stackoverflow.com/questions/29478672/how-to-conditionally-include-views-in-blade-with-laravel

@includeWhen($boolean, 'view.name', ['some' => 'data'])

View::make() will not work because BladeOne is not static.

**Comment by lexdubyna** [comment]
@jorgecc  I'm sorry, but my questions was about `@section`s and how to include a view file, if the `@section` is not defined in the child view. I don't see how the given answer is the solution to this problem.

**Comment by jorgecc** [comment]
You could try this code

@yield('footermissing',$this->runChild("view.name",[]))

**Comment by lexdubyna** [comment]
@jorgecc `@yield('footermissing',$this->runChild("view.name",[]))` - not working.
I have `@yield('content', $this->runChild('defaults/content.blade.php',[]))` in `base.blade.php` and `@section('content')` in child view, but `defaults/content.blade.php` is being loaded always, whether there is `@section('content')` in the child view or not.

**Comment by lexdubyna** [comment]
Also I can't `@include` a view in `@section` declaration. In `base.blade.php` I have
```
@section('content')
    @include('defaults/content.blade.php') // or @includefast
@show
```
And in a child view I have
```
@section('content')
    ...
@endsection
```
`defaults/content.blade.php` is also always shown whether there is `@section` in the child view or not.

**Comment by jorgecc** [comment]
@section/@endsection are mean to be used by @extend, not for @include. Also, you can't replace or stack @section() .   If you want to define a section, then you must do it with @extend, not with an include.


And about the other inquiry.

https://github.com/EFTEC/BladeOne/blob/master/examples/test2b.php

It calls the view

https://github.com/EFTEC/BladeOne/blob/master/examples/views/Test/hello2.blade.php

and this view extends the next view

https://github.com/EFTEC/BladeOne/blob/master/examples/views/Shared/newlayout.blade.php

We have the next code:

```
 @yield('footermissing',$this->runChild("Test.footermising"))
```
If the "footermissing" is missing then it includes the template corresponding.

So if

```
@section('footermissing')
    // ...
@endsection
````
is missing then it shows the **Test.footermising**

And if the section is present, then it shows the section.

But if we call:

```
@section('footermissing')
    @parent
@endsection
````
Then it includes the file regardless if the section is or not included.

**Comment by lexdubyna** [comment]
@jorgecc Yes, you are right, `@yield('footermissing',$this->runChild("Test.footermising"))` is working.
BUT if I have a custom directive or a function inside `Test.footermising`, then it is always being loaded.
This `Test.footermising` works as expected:
```
<h1>Test</h1>
<p>Hello world! I am a default content.</p>
```
This:
```
<h1>Test</h1>
@content
```
Or this
```
<h1>Test</h1>
{{ the_content() }}
```
is always being loaded

**Comment by lexdubyna** [comment]
Any updates on this issue?

**Comment by jorgecc** [comment]
I can't find the error running the example test2b:

https://github.com/EFTEC/BladeOne/blob/master/examples/test2b.php

# Section exists

In the view /examples/views/Test/hello2.blade.php

Has the section "footermissing" then it works correctly.  It shows the content of the section.

views/Test/hello2.blade.php
```
@extends('Shared.newlayout')


@section('footer')
    <p style="background-color: darkgrey">It is the footer. This footer is yield so it shouldn't contain a parent
        @parent this parent is completely ignored.
    </p>
@endsection

@section('footermissing')
    <p style="background-color: darkgrey">If you are reading this, then footermissing is not missing.
    </p>
    <p>Note: @@parent Don't add this one.</p>
@endsection
```
## Result: (1)

```
@yield('footermissing')
If you are reading this, then footermissing is not missing.

Note: @parent Don't add this one.
```
# Section does not exist

If in the same view /examples/views/Test/hello2.blade.php  we removed the section. Then it works as expected

views/Test/hello2.blade.php: 
```
@extends('Shared.newlayout')


@section('footer')
    <p style="background-color: darkgrey">It is the footer. This footer is yield so it shouldn't contain a parent
        @parent this parent is completely ignored.
    </p>
@endsection
```

## Result (2):
```
@yield('footermissing')
The fottermissing is missing hello world
Running the function myFunction()

```
The view **Shared.newlayout** has:

`@yield('footermissing',$this->runChild("Test.footermising"))`

It says, if the section  **footermissing** is missing in **hello2.blade.php**, then it calls the view **Test.footermissing**, if not, then it is not called (see Result: (1) )

View test.footermissing:

`<hr>**The fottermissing is missing {{$other}} {{myfunction()}} **</hr>`

**Comment by lexdubyna** [comment]
@jorgecc I'm sorry, but my code doesn't work this way. I'm gonna try to describe every detail.
First of all, I'm trying to use BladeOne with Wordpress.
My index.php file is:
```
$type = get_post_type();
$slug = get_post_field('post_name', get_post());
$dir = $type === 'page' ? 'page/' : 'single/';
$subDir = $type === 'page' ? $slug : $type;
$path = file_exists(__DIR__ . '/views/' . $dir . $subDir . '.blade.php') ? ($dir . $subDir) . '.blade.php' : 'base';

echo $blade->run($path, []);
```

My `views` folder is:
```
views

    defaults
        content.blade.php

    layout
        footer.blade.php
        header.blade.php
        sidebar.blade.php

    page
        home.blade.php
        test.blade.php

    shortcode
        test.blade.php

    single
        post.blade.php

    base.blade.php
```

`base.blade.php` :
```
<!DOCTYPE html>
<html lang="@lang">

<head>
	
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">

	{{ wp_head() }}

	@asset('app.css')
	
	@yield('head')

</head>

<body class="{{ post_body_class() }}">

	@include('layout/header.blade.php')
	
	<main>
		@yield('content', $this->runChild("defaults/content.blade.php"))
	</main>

	@include('layout/sidebar.blade.php')
	
	@include('layout/footer.blade.php')

	{{ wp_footer() }}
	
	@asset('app.js')

</body>

</html>
```

`page/home.blade.php` :
```
@extends('base')

@section('content')
	@wppost
	
		<h1>@title</h1>

		<button id="init">Init</button>

		<div id="app"></div>

		<a href="@acf('link')">acf link</a>

		@content
	
	@wpendpost
@endsection
```

`defaults/content.blade.php` :
```
<h1>Test</h1>
@content
```

With all the above code `defaults/content.blade.php` is always rendered on home page. BUT as soon as I change `defaults/content.blade.php` to
```
<h1>Test</h1>
{{-- @content --}}
```
or just remove `@content`, everything works as expected, and I see contents from `page/home.blade.php`. This thing happens only on the home page.

I enabled logging and `wp-content/debug.log` is empty, so there are no errors.

**Comment by jorgecc** [comment]
I added an example:
https://github.com/EFTEC/BladeOne/blob/master/examples/testbug.php

Also

a bladeone class  

https://github.com/EFTEC/BladeOne/blob/master/examples/BladeOneDummy.php

You could also try with @hassection("content")  @include("content") @endif()

https://laravel.com/docs/5.8/blade

**Comment by lexdubyna** [comment]
Thank you very much! I didn't know about `@hassection`.
```
@hasSection('content')
    @yield('content')
@else
    @include('defaults/content.blade.php')
@endif
```
This code finally works.
