### ISSUE TITLE
could we have an parameter for run that indicates if the section var will be truncated?

### ISSUE THREAD

**Issue by bassauer-storms-media** [EFTEC/BladeOne#93]
since a few bladeone versions the `run` method truncates the `sections` var:

`$this->sections = [];`

some of our older projects use to call `run` multiple times which leads us to inexisting sections  within some blade views. So we are not able to update bladeone to a newer version in those projects.

Could we have some paramerter for `run` that is able to tell the method not to reset the `sections` var to an empty array?

I guess we could also use `runChild` but this method always passes `forced=false` to the `runInternal` method as far as I can tell so I guess sometimes a template would not be recompiled

**Comment by jorgecc** [comment]
let's me check it.

**Comment by jorgecc** [comment]
Sorry for the delay but I am finishing a project & certification process.

**Comment by bassauer-storms-media** [comment]
thats quite fine - take your time :)

**Comment by jakewhiteley-gc** [comment]
@bassauer-storms-media Could I ask why you are running `run` multiple times? It Kinda feels like `run` should only be used for the main view template you are displaying, and everything else is just a partial within that layout.

Are you in a situation where you could you use `runChild` instead?

**Comment by jorgecc** [comment]
As for the issue, I tried to replicate and I was unable to find it. >_<

And why is it running so many times run. Run only is called on the main loop but also for the command @@each   Run is called if @@each is called without arguments (and it uses the variables of the main call.  @@each calls Runchild if is called with arguments.
