### ISSUE TITLE
Force the same file name

### ISSUE THREAD

**Issue by nam-co** [EFTEC/BladeOne#95]
Hola Jorge, gracias por este trabajo
I was wondering if there's a way to make the compiled file name the same as the blade filename? instead of the hash, I found "setCompiledExtension" but nothing to force the same name while using MODE_AUTO

Thanks

**Comment by nam-co** [comment]
Hola Jorge, disculpa, pero estoy recibiendo un error "Fatal error: Uncaught Error: Using $this when not in object context in..test.php."

Y en compiled/test.php me sale:
<?php $_shouldextend[1]=1; ?>
<?php $this->startSection('meta'); ?>

Pero en views/test.blade.php tango esto, no me debería salir todo el <!DOCTYPE htm.. etc en ves de $_shouldextend?
@extends('template')
@section('meta')

Disculpa por tanta preguntadera, pero en verdad quiero usarlo

**Comment by jorgecc** [comment]
hi:

you could change the extension and you could change to DEBUG_MODE, it stores a file that it is the same.

$blade->setCompiledExtension();

$blade=new BladeOne(null, null, BladeOne::MODE_DEBUG);

However, it does not keep the folder structure.

The method does    public function getCompiledFile($templateName = '')
