### ISSUE TITLE
$loop->index and $loop->iteration not working correctly

### ISSUE THREAD

**Issue by ed-iv** [EFTEC/BladeOne#96]
Hey there,

Was working with loop variables today, and am getting some issues involving $loop->index and $loop->iteration.

1. $loop->index is returning the 1-based index of current loop item (i.e. it is doing what $loop->iteration should be doing)

2. $loop->iteration does not appear to be implemented (just comes back as NULL)

Will take a look at source as time permits. Thanks for the package!

**Comment by jorgecc** [comment]
What do you want to do?.

Do you want to read the index from @for or  @foreach ?

**Comment by ed-iv** [comment]
Yea, I think Laravel only makes this available within @foreach (not 100% on that though). [As documented here](https://laravel.com/docs/5.8/blade#the-loop-variable), the $loop variable gives access to certain properties within the context of a particular loop. 

The list of properties has grown a bit larger in recent versions of Laravel to include a few that don't appear to be included in your implementation. As far as I can tell, these loop variables are initialized within each loop by your `compileForEach` method with a call to `addLoop`. The newer loop variables that I don't see in `addLoop` are: iteration, even, and odd.

Also `$loop->index` appears to be starting at 1 instead of 0. I see it being initialized to 0 in `addLoop` though so it must be incremented prior to the first loop somehow?

**Comment by jorgecc** [comment]
Done in #3.32

- 2019-12-21 3.32 
    * For #96 added $loop->even and $loop->odd and $loop->iteration
    * Also, **$loop->index now starts with 0 instead of 1**
