### ISSUE TITLE
Set default @yield via include file

### ISSUE THREAD

**Issue by hoangnamitc** [EFTEC/BladeOne#97]
Hi guys,

How to i can set value default for @yield() with file include.

In Blade Laravel do it:
![image](https://user-images.githubusercontent.com/7042462/66252267-a8309900-e783-11e9-965d-fb9cb4786135.png)

Thanks !

**Comment by jakewhiteley-gc** [comment]
@hoangnamitc You can do this with BladeOne as well.

A facade like Laravel's `View` is up to you to make in your app, but if you have anyway of getting access to your BladeOne instance inside your .blade.php file, could you not just use something similar to:


````php
// Assuming $blade is available in your setup
@yield('header', $blade->runChild('partials.header')
````

If you would like to know how to get your blade instance available, try looking up IoC containers, how laravel Facades work, or even just pass the instance into your view as data.

Hope that helps!
