### ISSUE TITLE
Php array dot notation

### ISSUE THREAD

**Issue by farhanianz** [EFTEC/BladeOne#98]
It's a great library. Is there a way I can access array in bladeone template by dot notation? Like this one - 

````php
{{ $array.key }} to display $array['key']  
````

**Comment by jakewhiteley-gc** [comment]
@farhanianz Not really sorry!

Although it would be possible to write a check into the library and give you dot notation, it goes against the spirit of Blade templating language: Blade provides templating sugar, but does not add language-level sugar or change how you interact with normal PHP.

If dot notation is a must have for you, have you tried the Twig templating engine?

It has some similarities, but does not allow and native PHP to be run inside templates.

**Comment by jorgecc** [comment]
I agree.   Everything inside {{ }} is practically php, so it reduces the learning curve considerably but it also increases the performance and the parser.
