### ISSUE TITLE
Missing keys log is always rewriting with only the last key

### ISSUE THREAD

**Issue by PaiCthulhu** [EFTEC/BladeOne#99]
on BladeOne.php at line 3112:
`$fp = \fopen($this->missingLog, 'w');`
The `'w'` is fixed instead of the `$mode` variable being used, so the missing keys log always shows only the last missing key.

###### Saludos de un hermano brasileño. ¡Gracias por mantener la biblioteca actualizada!

**Comment by jorgecc** [comment]
Done.
